server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/maycode-ses
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update